services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace:cached
      - media-volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    internal: false

volumes:
  postgres_data:
  media-volume: