services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity #uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-8000} --workers 4 --reload
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - .:/workspace:cached
      - media-volume:/app/media

volumes:
  media-volume:
